version: '3.9'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - CHECK_POLICY=OFF
      - SA_PASSWORD=A!VeryComplex123Password
      - MSSQL_SA_PASSWORD=A!VeryComplex123Password
    ports:
      - 1433:1433
